### ISSUE TITLE
add destination path variable

### ISSUE THREAD

**Issue by timomayer** [jakejarvis/s3-sync-action#3]
if you do not want to sync to root of a bucket it is necessary that you can also define the s3 bucket path to sync to

**Comment by jakejarvis** [comment]
Adding a path to the end of the bucket name should do the trick, like `AWS_S3_BUCKET: 'mywebsite.com/public'`. But you're definitely correct that this isn't intuitive and would be a good optional variable to have — I'll add one as soon as I get a chance!

Please let me know if that doesn't work in the meantime. :)

**Comment by tomaszcoding** [comment]
Hi,

first of all thanks for the action - it's very helpful!

If I specify **destination directory** and use **--delete** flag, will all files in the bucket be deleted (which don't exist in the build) or just the ones in the destination directory?
