### ISSUE TITLE
sh: .git/FETCH_HEAD: Permission denied

### ISSUE THREAD

**Issue by derekssmith** [jakejarvis/s3-sync-action#9]
I am trying to use this action, but am getting this error.  Any ideas on what is causing it?

```
sh: .git/FETCH_HEAD: Permission denied
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --exclude: expected 1 argument
##[error]Docker run failed with exit code 2
```

**Comment by jakejarvis** [comment]
Sorry for the trouble! It looks like it's having trouble with the `--exclude` flag — are you trying to exclude multiple files/folders? If so you need to have multiple `--exclude` for each, like:

`args: --exclude '.git/*' --exclude 'private.txt' --exclude 'secrets/*'`

...in other words, one `--exclude` per exclusion, and single quotes around each of the patterns. The CLI is pretty picky.

Let me know if that makes zero sense or if I'm guessing wrong! :)

**Comment by derekssmith** [comment]
Thanks for getting back so quickly.  I may not even need the exclude flag.  I was just following the example.  The folder I am syncing is not the root repository folder so there shouldn't be a `.git` file.  I am trying to just sync the `./bin` folder to a path in S3.

**Comment by jakejarvis** [comment]
You're correct, you shouldn't need it at all in that case (and probably most cases, honestly) — I'll make this more clear in the readme, thanks for the heads up! The problem might have been the tildes instead of single quotes around the `.git/*` but that should be irrelevant now if everything else works.

**Comment by derekssmith** [comment]
Thanks!  After I posted this I saw the tildes, and am trying it with single quotes.  I was waiting until it completed to report back whether or not that was the fix.  I will let you know.

**Comment by derekssmith** [comment]
It was the tildes.  It is working now.  Thanks!

**Comment by jakejarvis** [comment]
No worries, let me know if anything else weird comes up! 👍

**Comment by Parag-S-Salunkhe** [comment]
hey jake, I am trying to use this action and its giving me an error as

sh: /: Permission denied
my args is args: --acl private --follow-symlinks --delete

and others have used this and its working for them.  I searched up and some people are having ssame issue so they suggested to use this action shallwefootball/s3-upload-action, which is working for me BUT i have to keep s3 bucket public. 
your guidance will be of great help, thanks.
